version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_USER: avito
      POSTGRES_PASSWORD: avito
      POSTGRES_DB: avito
    ports:
      - "5436:5432"
    volumes:
      - ./initDB.sql:/docker-entrypoint-initdb.d/init.sql

  user-balance:
    container_name: user-balance
    ports:
      - "8080:8080"
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - "db"
